### ISSUE TITLE
Graceful handling of badNonce error, retry with new nonce

### ISSUE THREAD

**Issue by kellpossible** [djc/instant-acme#62]
https://github.com/letsencrypt/pebble?tab=readme-ov-file#invalid-anti-replay-nonce-errors

**Comment by kellpossible** [comment]
While it should be possible to handle at a higher level, it seems to me like something that could be a good candidate to handle inside the ACME client, as the error could present itself in many places.

**Comment by djc** [comment]
Sounds good, want to submit a PR?

**Comment by kellpossible** [comment]
Hi! I don't have time at the moment unfortunately, but if it crops up in
production I'm sure it will become a priority. Feel free to close, at least
it's here for the record

**Comment by nick96** [comment]
I had a go at this in https://github.com/djc/instant-acme/pull/65 because I ran into it trying to do some testing against pebble. Let me know what you think.
